instance_id: "58f400d0-9ed4-4d58-ab57-5cb343fe8e46"
api_key: "test_key_123"
api_endpoint: "http://localhost:3000"

mssql:
  host: "172.28.28.203"
  port: 1433
  user: "sa"
  password: "SQLAdmin1"
  radiology_db: "RADSpaRISRadiologyDB"
  reporting_db: "RADSpaRISReportingDB"

backfill:
  enabled: true
  from_date: "2025-01-01"
  to_date: "2025-01-31"
  batch_size: 500

polling:
  finished_reports_seconds: 30
  reference_data_hours: 24

logging:
  level: "INFO"
