import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { error as apiError } from '@/lib/api-response';
import React from 'react';
import { Document, Page, Text, View, StyleSheet, renderToStream, Font } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 10 },
  header: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 40 },
  title: { fontSize: 24, fontWeight: 'bold', color: '#1e3a8a' },
  invoiceInfo: { textAlign: 'right' },
  clientInfo: { marginBottom: 30 },
  sectionTitle: { fontSize: 12, fontWeight: 'bold', marginBottom: 5 },
  table: { width: '100%', marginBottom: 30 },
  tableHeader: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#000', paddingBottom: 5, marginBottom: 5, fontWeight: 'bold' },
  tableRow: { flexDirection: 'row', marginBottom: 5 },
  col1: { width: '40%' },
  col2: { width: '20%', textAlign: 'right' },
  col3: { width: '20%', textAlign: 'right' },
  col4: { width: '20%', textAlign: 'right' },
  summary: { marginTop: 20, borderTopWidth: 1, borderTopColor: '#000', paddingTop: 10, alignItems: 'flex-end' },
  summaryRow: { flexDirection: 'row', marginBottom: 5, width: 200, justifyContent: 'space-between' },
  summaryLabel: { fontWeight: 'bold' },
  totalRow: { flexDirection: 'row', marginTop: 5, paddingTop: 5, borderTopWidth: 2, borderTopColor: '#000', width: 200, justifyContent: 'space-between' },
  totalLabel: { fontWeight: 'bold', fontSize: 12 },
  totalValue: { fontWeight: 'bold', fontSize: 12, color: '#1e3a8a' },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', color: 'grey', fontSize: 8, borderTopWidth: 1, borderTopColor: '#ddd', paddingTop: 10 }
});

const InvoicePDF = ({ invoice }: { invoice: any }) => {
  const formatCur = (num: number) => `BDT ${Number(num).toLocaleString()}`;
  const formatDate = (date: Date) => new Date(date).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.title}>INVOICE</Text>
            <Text style={{ marginTop: 5 }}>Care360 TeleRadiology Billing</Text>
            <Text>123 Medical Hub, Dhaka</Text>
            <Text>contact@rsb.com.bd</Text>
          </View>
          <View style={styles.invoiceInfo}>
            <Text style={{ fontWeight: 'bold' }}>Invoice #: {invoice.invoice_number}</Text>
            <Text>Date: {formatDate(invoice.finalized_at || invoice.created_at)}</Text>
            <Text>Period: {formatDate(invoice.period_start)} - {formatDate(invoice.period_end)}</Text>
          </View>
        </View>

        <View style={styles.clientInfo}>
          <Text style={styles.sectionTitle}>Billed To:</Text>
          <Text>{invoice.client.name}</Text>
          <Text>{invoice.client.contact_email || 'No email provided'}</Text>
        </View>

        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={styles.col1}>Study Type</Text>
            <Text style={styles.col2}>Quantity</Text>
            <Text style={styles.col3}>Unit Price</Text>
            <Text style={styles.col4}>Total</Text>
          </View>
          {invoice.lines.map((line: any, idx: number) => (
            <View key={idx} style={styles.tableRow}>
              <Text style={styles.col1}>{line.type}</Text>
              <Text style={styles.col2}>{line.qty}</Text>
              <Text style={styles.col3}>{formatCur(line.unit_price)}</Text>
              <Text style={styles.col4}>{formatCur(line.total)}</Text>
            </View>
          ))}
        </View>

        <View style={styles.summary}>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Subtotal:</Text>
            <Text>{formatCur(invoice.subtotal)}</Text>
          </View>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Previous Due:</Text>
            <Text>{formatCur(invoice.previous_due)}</Text>
          </View>
          <View style={styles.totalRow}>
            <Text style={styles.totalLabel}>Total Due:</Text>
            <Text style={styles.totalValue}>{formatCur(invoice.total_due)}</Text>
          </View>
        </View>

        <View style={styles.footer}>
          <Text>Please make checks payable to "Care360 TeleRadiology".</Text>
          <Text>Generated by TeleRadiology Billing Automation Platform</Text>
        </View>
      </Page>
    </Document>
  );
};

export async function GET(req: Request, { params }: { params: { id: string } }) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user) return apiError('UNAUTHORIZED', 'Unauthorized', 401);

    const invoice = await prisma.invoice.findUnique({
      where: { id: params.id },
      include: {
        client: true,
        lines: { orderBy: { type: 'asc' } }
      }
    });

    if (!invoice) return apiError('NOT_FOUND', 'Invoice not found', 404);

    const stream = await renderToStream(<InvoicePDF invoice={invoice} />);
    
    // Return standard stream Response
    return new Response(stream as any, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `inline; filename="Invoice_${invoice.invoice_number}.pdf"`
      }
    });
  } catch (err: any) {
    console.error('[INVOICE_PDF_GET]', err);
    return apiError('INTERNAL_ERROR', 'Failed to generate PDF', 500);
  }
}
